name: Build iOS IPA for RustDesk

on:
  push:
    tags:
      - 'v*'  # 在推送以 'v' 开头的 tag 时触发
  workflow_dispatch:  # 允许手动触发

env:
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-rustdesk-ios:
    name: Build RustDesk iOS IPA (Unsigned)
    runs-on: macos-13
    needs: [generate-bridge]
    
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install dependencies
        run: |
          brew install nasm yasm

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Patch Flutter
        run: |
          cd $(dirname $(dirname $(which flutter)))
          [[ "3.24.5" == ${{env.FLUTTER_VERSION}} ]] && git apply ${{ github.workspace }}/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        run: |
          if ! $VCPKG_ROOT/vcpkg \
            install \
            --triplet arm64-ios \
            --x-install-root="$VCPKG_ROOT/installed"; then
            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
              echo "$_1:"
              echo "======"
              cat "$_1"
              echo "======"
              echo ""
            done
            exit 1
          fi
        shell: bash

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: aarch64-apple-ios
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rustdesk-lib-cache-ios
          key: aarch64-apple-ios

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Build RustDesk library
        run: |
          rustup target add aarch64-apple-ios
          cargo build --features flutter,hwcodec --release --target aarch64-apple-ios --lib

      - name: Build iOS Archive
        run: |
          cd flutter
          # 构建 iOS 应用（不生成 IPA）
          flutter build ios --release --no-codesign
          
          # 检查生成的文件
          echo "=== 检查构建目录结构 ==="
          find build/ios -type f -name "*.app" | head -10
          ls -la build/ios/iphoneos/

      - name: Create IPA manually from .app file
        run: |
          cd flutter
          
          # 查找 .app 文件
          APP_PATH=$(find build/ios/iphoneos -name "*.app" -type d | head -1)
          
          if [ -z "$APP_PATH" ]; then
            echo "错误：未找到 .app 文件"
            find build/ios -type f -name "*.app" || echo "未找到任何 .app 文件"
            exit 1
          fi
          
          echo "找到 .app 文件: $APP_PATH"
          
          # 创建 IPA 目录
          mkdir -p build/ios/ipa
          
          # 创建临时目录结构
          mkdir -p temp_ipa/Payload
          
          # 复制 .app 到 Payload
          cp -r "$APP_PATH" temp_ipa/Payload/
          
          # 进入临时目录并创建 IPA
          cd temp_ipa
          zip -r ../build/ios/ipa/RustDesk.ipa .
          
          # 返回并清理
          cd ..
          rm -rf temp_ipa
          
          # 检查生成的 IPA
          echo "=== 生成的 IPA 文件 ==="
          ls -la build/ios/ipa/
          echo "IPA 文件大小:"
          du -h build/ios/ipa/RustDesk.ipa

      - name: Get version information
        id: version_info
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            TAG_NAME=${GITHUB_REF#refs/tags/}
          else
            VERSION="nightly-$(date +%Y%m%d)"
            TAG_NAME="nightly-$(date +%Y%m%d)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "版本: $VERSION"
          echo "Tag: $TAG_NAME"

      - name: Rename IPA with version
        run: |
          cd flutter/build/ios/ipa
          cp RustDesk.ipa "RustDesk-${{ env.VERSION }}-unsigned.ipa"
          ls -la

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-ios-${{ env.VERSION }}-unsigned
          path: flutter/build/ios/ipa/RustDesk-${{ env.VERSION }}-unsigned.ipa
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: flutter/build/ios/ipa/RustDesk-${{ env.VERSION }}-unsigned.ipa
          draft: false
          prerelease: false
